# Generated by Django 4.0.2 on 2022-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AboutImage',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
